@echo off
echo Iniciando emulador Tablet...
start "" "%LOCALAPPDATA%\Android\Sdk\emulator\emulator.exe" -avd Tablet
echo Esperando que el emulador inicie...
timeout /t 20 /nobreak
echo Ejecutando Expo...
npx expo start --android
