@echo off
echo Iniciando emulador Xiaomi Redmi Pad 2...
start "" "%LOCALAPPDATA%\Android\Sdk\emulator\emulator.exe" -avd Xiaomi_Redmi_Pad_2_API_33
echo Esperando que el emulador inicie...
timeout /t 20 /nobreak
echo Ejecutando Expo...
npx expo start --android
